name: Recently used
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run metrics action
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: |
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
